# Copyright (C) 2025 Soumyadeep Ghosh <soumyadeepghosh2004@zohomail.in>
# All Rights Reserved.

name: Deploy to Cloud Run

on:
  push:
    branches:
      - assesment
  workflow_dispatch:

jobs:
  deploy:
    environment: "Assesment"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate with GCloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/pharmadocsai

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy pharmadocsai \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/pharmadocsai \
          --region asia-south1 \
          --platform managed \
          --allow-unauthenticated
